org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.93
neo_version_range=[26.1.2.93,)
loader_version_range=[4,)

mod_id=buff_particle_remover
mod_name=Buff Particle Remover
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=org.hp
mod_authors=hp
mod_description=隐藏第一人称 Buff 粒子
