org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
fabric_loader_version=0.19.3
loom_version=1.10.5

mod_id=buff_particle_remover
mod_name=Buff Particle Remover
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=org.hp
mod_authors=hp
mod_description=隐藏第一人称 Buff 粒子
